config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  get 'articles/create'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'home/top'
  # get 'users/dash_boards'

  devise_scope :user do
    root "users/sessions#new"

    put 'confirmation', to: 'users/confirmations#show', as: :back_confirmation
  end

  devise_for :users,
  controllers: {
      confirmations: 'users/confirmations',
      dashboards: 'users/dash_boards',
    }

  namespace :users do
    resources :dash_boards, only: [:index]
    resources :articles
  end

  
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { in: 1..10 }
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  def is_confirmation_period_expired?
    # メールアドレス確認メール有効期限チェック(期限はconfig/initializers/devise.rbのconfirm_withinで設定)
    self.confirmation_period_expired?
  end
end

app/controllers/users/articles_controller.rb
module Users
  class ArticlesController < ApplicationController

    # before_action :set_user
    before_action :set_article, only: %i(show edit update destroy)
    before_action :authenticate_user!
    # before_action :correct_user


    def index
      @articles = Article.all
    end
  
    def show
      @article = Article.find(params[:id])
    end

    def new
      @user = User.find(params[:id])
      @article = Article.new
    end

    def create
      @article = Article.new(article_params) 
      unless params[:article][:title] == "" || params[:article][:content] == ""
        @article = @article.update(user_id: params[:id])
        @article = Article.last
        @article.image = "article_#{@article.id}.png"
        File.binwrite("public/images/article_#{@article.id}.png", params[:article][:image].read)
        @article.save
        flash[:success] = "記事を新規作成しました。"
        redirect_to users_articles_url
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @article.update(article_params)
        flash[:success] = "タスクを更新しました。"
        redirect_to users_articles_url
      else
        render :edit
      end
    end
    
    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      flash[:success] = "記事を削除しました。"
      redirect_to users_articles_url
    end

    private

    def article_params
     params.require(:article).permit(:title, :content, :image)
    end
    
    # def set_user
    #   @user = User.find(params[:user_id])
    # end

    def set_article
      @article = Article.find(params[:id])
      unless @article.user_id == current_user.id
        flash[:danger] = "権限がありません。"
        redirect_to user_articles_url @user
      end
    end
    
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end
  def show
    self.resource = resource_class.find_by_confirmation_token(params[:confirmation_token])

    if resource.nil? || resource.confirmed?
      # トークンが不正な場合、アカウント登録(パスワード登録)が済んでいる場合
      self.resource = resource_class.confirm_by_token(params[:confirmation_token])
      render :show
    elsif resource.is_confirmation_period_expired?
      # アカウント登録メールの期限が切れた場合
      resource.errors.add(:email, :confirmation_period_expired,
        period: Devise::TimeInflector.time_ago_in_words(resource_class.confirm_within.ago))
      render :show
    else
      # activate
      self.resource = resource_class.confirm_by_token(params[:confirmation_token])
      redirect_to new_user_session_path, notice: 'メールアドレスを確認しました。'
    end
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/dash_boards_controller.rb
module Users
  class DashBoardsController < ApplicationController
    def index
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def dash_boards
    end
  end
  

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/users/articles/_form.html.erb
<%= form_with(model: @article, url: users_articles_path(@user, id: params[:id]), local: true) do |f| %>
  <%# <%= render 'shared/error_messages', object: @user %>

  <%= f.label :title, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :content, class: "label-#{yield(:class_text)}" %>
  <%= f.text_area :content, class: "form-control" %>

  <%= f.label :image, class: "label-#{yield(:class_text)}" %>
  <%= f.file_field :image, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/articles/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'article-edit') %>
<% provide(:button_text, '更新') %>
<h1>記事情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @article, url: users_article_path(@user, id: params[:id]), method: :patch, local: true) do |f| %>
      <%# <%= render 'shared/error_messages', object: @user %>

      <%= f.label :title, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :content, class: "label-#{yield(:class_text)}" %>
      <%= f.text_area :content, class: "form-control" %>

      <%= f.label :image, class: "label-#{yield(:class_text)}" %>
      <%= f.file_field :image, class: "form-control" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>
    <%= link_to "戻る", users_articles_path %>
  </div>
</div>

app/views/users/articles/index.html.erb
<% provide(:title, "articles") %>
<div class="mx-auto" style="width: 200px;">
<h1>記事一覧</h1>
<%= link_to "新規作成", new_users_article_path(id: current_user.id), class: "btn btn-lg btn-primary pull-right" %>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    
    <table class="table table-hover" id="table-tasks">
      <thead>
        <tr>
          <th>詳細</th>
          <th>タイトル</th>
          <th>内容</th>
          <th>画像</th>
          <th>編集・削除</th>
        </tr>
      </thead>

      <tbody>
        <% @articles.each do |a| %>
          <tr>
            <td><%= link_to "詳細", users_article_path(id: a.id), class: "btn btn-primary" %></td>
            <td><%= a.title %></td>
            <td><%= a.content %></td>
            <td><%= image_tag "/images/#{a.image}" %></td>
            <td>
              <%= link_to "編集", edit_users_article_path(id: a.id), class: "btn btn-success" %>
              <%= link_to "削除", users_article_path(id: a.id), method: :delete,
              # data: { confirm: "「#{a.title}」を削除します。よろしいですか？" }, 
              class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>    
</div>

app/views/users/articles/new.html.erb
<% provide(:title, 'New') %>
<% provide(:class_text, 'article-new') %>
<% provide(:button_text, '新規作成') %>
<h1>記事の新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @article, url: users_articles_path(@user, id: params[:id]), local: true) do |f| %>
      <%# <%= render 'shared/error_messages', object: @user %>

      <%= f.label :title, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :content, class: "label-#{yield(:class_text)}" %>
      <%= f.text_area :content, class: "form-control" %>

      <%= f.label :image, class: "label-#{yield(:class_text)}" %>
      <%= f.file_field :image, class: "form-control" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>
    <%= link_to "戻る", users_articles_path %>
  </div>
</div>

app/views/users/articles/show.html.erb
<% provide(:title, "articles") %>
<div class="mx-auto" style="width: 200px;">
<h1>記事詳細</h1>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table table-hover" id="table-tasks">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>内容</th>
          <th>画像</th>
        </tr>
      </thead>

      <tbody>       
        <tr>
          <td><%= @article.title %></td>
          <td><%= @article.content %></td>
          <td><%= image_tag "/images/#{@article.image}" %></td>
        </tr>

        
      </tbody>
      
    </table>
    <div class="mx-auto" style="width: 200px;">
      <%= link_to "編集", edit_users_article_path(id: @article.id), class: "btn btn-success" %>
      <%= link_to "削除", users_article_path(id: @article.id), method: :delete,class: "btn btn-danger" %><br>
      <%= link_to "記事一覧へ戻る", users_articles_path, class: "btn btn-lg btn-primary pull-right" %>
    </div>
  </div>    
</div>